name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: ['22']

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 5001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: |
            backend/yarn.lock
            frontend/yarn.lock

      # Backend
      - name: Install backend deps
        working-directory: backend
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Run backend tests
        working-directory: backend
        run: |
          yarn test --ci --watchAll=false

      # Frontend (optional: build to ensure it compiles)
      - name: Install frontend deps
        working-directory: frontend
        run: |
          yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: frontend
        run: |
          rm -rf build
          yarn build
