name: FoodDelivery CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install backend deps
        working-directory: backend
        run: |
          npm ci

      - name: Run backend tests
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.FOOD_MONGO_URI }}
          JWT_SECRET: ${{ secrets.FOOD_JWT_SECRET }}
          PORT: ${{ secrets.FOOD_PORT }}
        run: npm test

  deploy:
    name: Deploy to EC2
    needs: test
    runs-on: self-hosted  # your EC2 runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure folders on EC2
        run: |
          mkdir -p /home/ubuntu/apps/fooddelivery/backend
          mkdir -p /home/ubuntu/apps/fooddelivery/frontend/build

      - name: Deploy backend (FoodDelivery)
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.FOOD_MONGO_URI }}
          JWT_SECRET: ${{ secrets.FOOD_JWT_SECRET }}
          PORT: ${{ secrets.FOOD_PORT }}
        run: |
          # install deps and write .env
          npm ci
          cat > .env <<EOF
          NODE_ENV=production
          MONGO_URI=${MONGO_URI}
          JWT_SECRET=${JWT_SECRET}
          PORT=${PORT}
          EOF

          # move code to app dir
          rsync -a --delete ./ /home/ubuntu/apps/fooddelivery/backend/

          # restart only this app (don't touch TaskManager)
          pm2 delete food-backend || true
          pm2 start server.js --name food-backend --time --cwd /home/ubuntu/apps/fooddelivery/backend
          pm2 save

      - name: Build + publish frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
          rsync -a --delete build/ /home/ubuntu/apps/fooddelivery/frontend/build/

      - name: Reload nginx (optional but recommended)
        run: sudo systemctl reload nginx
